### ISSUE TITLE
Upgrade to Toplo's main branch?

### ISSUE THREAD

**Issue by tinchodias** [Ducasse/Myg#22]
Toplo's main branch seems good choice for Myg development branch. Do you agree @plantec ?

**Comment by Ducasse** [comment]
I think that it would be good to have the current dev toplo branch merged back into master.
For when is it planned?

**Comment by Ducasse** [comment]
Else inside it makes sense that we use the latest to beta test.

**Comment by plantec** [comment]
The main branch will not be merged in the master one. I will set main as the default branch. and let the master unchanged.

**Comment by Ducasse** [comment]
Why?
I would kill one because this is super confusing. 
At the end Bloc/Toplo should have
- master
- dev
- pharo12, pharo11
- integration 

Like in microdown or Spec. 
https://github.com/pharo-spec/Spec/
https://github.com/pillar-markup/Microdown/branches

The idea (from memory) is 
- all the dev of a current version is merged back in dev
- When dev is considered stable it is merged in master
- for each version of Pharo there is a branch in which the master is pushed.
- the integration branch is for testing that the integration in Pharo is working and letting scripts run.

BTW master would be better because all the main branches in Pharo are called master.
This is easier for the dependency

**Comment by plantec** [comment]
Thanks, I didn't know these rules.
well, I do not have the time to merge and there is no benefit to do so.

Current toplo/master could be renamed as firstTry or something like that.
and according to your comment, toplo main can be renamed as master. 
is it ok like that ?

**Comment by Ducasse** [comment]
Sure :)

**Comment by tinchodias** [comment]
Time passed and now it should depend on Toplo:master

**Comment by tinchodias** [comment]
I think this is important, because now it's loading too old Toplo and Bloc

**Comment by Enzo-Demeulenaere** [comment]
done in commit 7b7fe7dd63bdeb766f1287d2ef30ea67b6987bdd

**Comment by tinchodias** [comment]
@Enzo-Demeulenaere in that commit I see there are also noise changes due to Tonel version. This happens when contributors commit from Pharo 11 (default for Tonel is version 1) and from Pharo >=12 (default version is 3 or 2, not sure).

In Bloc, Toplo and other repos we made explicit the Tonel version 1, because it is available from Pharo 11 to 13. For the case you are interested, the change is simple:
https://github.com/pharo-graphics/Toplo/commit/19c83f6f93e527f1f6a8464abedb419d10b1d1a6

After that change, all future changes will be using the same version of Tonel.

**Comment by Ducasse** [comment]
Tx for checking.
